config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root "soliloquies#top"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      patch :out
    end

    member do
      get :following, :followers
      get :quit
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :messages, :only => [:create]

  resources :rooms, :only => [:create, :show, :index]

  resources :relationships, only: [:create, :destroy]

  resources :soliloquies do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get "about" => "soliloquies#about"

  get "first" => "users#first"
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  validates :comment, presence: true, length: { in: 2..200 }

  belongs_to :user
  belongs_to :soliloquy
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @soliloquy = Soliloquy.find(params[:soliloquy_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.user_id = current_user.id
    @post_comment.soliloquy_id = @soliloquy.id
    @post_comment.save
  end

  def destroy
    @soliloquy = Soliloquy.find(params[:soliloquy_id])
    @post_comment = PostComment.find_by(id: params[:id], soliloquy_id: params[:soliloquy_id])
    @post_comment.destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_post_comment.html.erb
<div class="comment-list bt style-2" id="comments">
  <div class="float-wrapper">
    <h4 class="comment-count"><%= soliloquy.post_comments.count %>件コメント</h2>
  </div>
<%= render 'layouts/errors', resource: @post_comment %>
									  	<% if flash[:notice] %>
											<div class="flash">
												<%= flash[:notice] %>
											</div>
										<% end %>


	<table id="js-table-comment", class="table">
		<% soliloquy.post_comments.each do |post_comment| %>
			<% if post_comment.user.is_deleted == "Invaild" %>
			<% else %>
			<tr>
				   	<td width="120">
				    	<%= link_to user_path(post_comment.user) do %>
				    		<%= attachment_image_tag(post_comment.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: "100x100") %>
				    	<% end %>
				    </td>
			    	<td width="150">
				    	<%= post_comment.user.name %>
				    			<p><%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
				    	<p><% if post_comment.user.id == current_user.id %>
		      					<%= link_to soliloquy_post_comment_path(soliloquy, post_comment), method: :delete, class: "btn-sm btn-danger", remote: true do %>
		      						<i>削除</i>
		      					<% end %>
		    				<% end %>
		    			</p>
	    			</td>
					<td>
	        	<%= post_comment.comment %>
					</td>
				</tr>
			<% end %>
		<% end %>
	<table>
</div>

app/views/post_comments/create.js.erb
$('#comments').html("<%= j(render 'post_comments/post_comment',soliloquy: @soliloquy, post_comment: @post_comment) %>");
$('#post_comment_comment').val('');

app/views/post_comments/destroy.js.erb
$('#comments').html("<%= j(render 'post_comments/post_comment',soliloquy: @soliloquy, post_comment: @post_comment) %>");