config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root "soliloquies#top"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      patch :out
    end

    member do
      get :following, :followers
      get :quit
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :messages, :only => [:create]

  resources :rooms, :only => [:create, :show, :index]

  resources :relationships, only: [:create, :destroy]

  resources :soliloquies do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get "about" => "soliloquies#about"

  get "first" => "users#first"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true, length: { in: 2..20 }
  validates :first_name, presence: true, length: { in: 2..20 }
  validates :kana_last_name, presence: true, length: { in: 2..20 }
  validates :kana_first_name, presence: true, length: { in: 2..20 }
  validates :introduction, presence: true, length: { in: 2..1000 }
  # validates :profile_image_id, presence:true
  validates :for_what_application, presence: true, length: { in: 2..1000 }
  validates :message_level, presence: true, length: { in: 2..1000 }
  validates :ignore_character, presence: true, length: { in: 2..1000 }
  validates :occupation, presence: true, length: { in: 2..50 }
  validates :think_to_job, presence: true, length: { in: 2..1000 }
  validates :want_job_time, presence: true, length: { in: 2..50 }
  validates :think_job_relationship, presence: true, length: { in: 2..1000 }
  validates :can_offer_job, presence: true, length: { in: 2..1000 }
  validates :target_income, presence: true, length: { in: 2..1000 }
  validates :what_want_learn, presence: true, length: { in: 2..1000 }
  validates :like_other_job, presence: true, length: { in: 2..1000 }
  validates :what_desire_love, presence: true, length: { in: 2..1000 }
  validates :how_did_life, presence: true, length: { in: 2..1000 }
  validates :past_failures, presence: true, length: { in: 2..1000 }
  validates :basic_experience, presence: true, length: { in: 2..1000 }
  validates :what_require, presence: true, length: { in: 2..1000 }
  validates :my_personality, presence: true, length: { in: 2..1000 }
  validates :can_offer_personality, presence: true, length: { in: 2..1000 }
  validates :request_relationship_spirit, presence: true, length: { in: 2..1000 }
  validates :interested_by_given, presence: true, length: { in: 2..1000 }

  has_many :post_comments, dependent: :destroy
  has_many :soliloquies, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :active_relationships,  class_name: "Relationship",
                                   foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  attachment :profile_image

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end


  def kana_name
    kana_last_name + kana_first_name
  end

  def self.guest
    find_or_create_by!(

      last_name: 'ゲスト田中',
      first_name: 'ゲストたかし',
      kana_last_name: 'ゲストタナカ',
      kana_first_name: 'ゲストタカシ',
      introduction: 'ゲストログインです',
      for_what_application: 'ゲストログインです',
      message_level: 'ゲストログインです',
      ignore_character: 'ゲストログインです',
      occupation: 'ゲストログインです',
      think_to_job: 'ゲストログインです',
      want_job_time: 'ゲストログインです',
      think_job_relationship: 'ゲストログインです',
      can_offer_job: 'ゲストログインです',
      target_income: 'ゲストログインです',
      what_want_learn: 'ゲストログインです',
      like_other_job: 'ゲストログインです',
      what_desire_love: 'ゲストログインです',
      how_did_life: 'ゲストログインです',
      past_failures: 'ゲストログインです',
      basic_experience: 'ゲストログインです',
      what_require: 'ゲストログインです',
      my_personality: 'ゲストログインです',
      can_offer_personality: 'ゲストログインです',
      request_relationship_spirit: 'ゲストログインです',
      interested_by_given: 'ゲストログインです',
      # is_deleted: 'Availble',

      email: 'guest@example.com'

    ) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def name
    last_name + first_name
  end

  # Availble:稼働中 Invaild:退会済み
  enum is_deleted: { Availble: false, Invaild: true }

  def active_for_authentication?
    super && (is_deleted == "Availble")
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i(update destroy)
  before_action :authenticate_user!

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :authenticate_user!

  def new_guest
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def quit
    @user = User.find(params[:id])
    if @user == User.guest
      flash[:notice] = "ゲストログインはユーザー情報を編集できません"
      redirect_to user_path
    end
  end

  def out
    @user = current_user
    @user.update(is_deleted: "Invaild")
    reset_session
    flash[:notice] = "退会完了しました"
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
    if @user.is_deleted == "Invaild"
      flash[:notice] = "退会したユーザーです"
      redirect_to root_path
    else

      @soliloquies = @user.soliloquies

      @current_user_entry = Entry.where(user_id: current_user.id)
      @user_entry = Entry.where(user_id: @user.id)

      if @user.id == current_user.id
      else
        @current_user_entry.each do |cu|
          @user_entry.each do |u|
            if cu.room_id == u.room_id
              @is_room = true
              @room_id = cu.room_id
            end
          end
        end
        if @is_room
        else
          @room = Room.new
          @entry = Entry.new
        end
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "ログインユーザーのものではない"
      redirect_to user_path
    elsif @user == User.guest
      flash[:notice] = "ゲストログインはユーザー情報を編集できません"
      redirect_to user_path
    else

    end
  end

  def index
    @users = User.all
    @soliloquies = Soliloquy.all
  end

  def update
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "ログインユーザーのものではありません"
      redirect_to user_path(current_user.id)
    end
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を変更完了しました"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def following
    @title = "following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name,
                                 :kana_last_name, :kana_first_name,
                                 :email, :encrypted_password,
                                 :profile_image, :introduction,
                                 :for_what_application,
                                 :message_level, :ignore_character,
                                 :occupation, :think_to_job,
                                 :want_job_time, :think_job_relationship,
                                 :can_offer_job, :target_income,
                                 :what_want_learn, :like_other_job,
                                 :what_desire_love, :how_did_life,
                                 :past_failures, :basic_experience,
                                 :what_require, :my_personality,
                                 :can_offer_personality,
                                 :request_relationship_spirit,
                                 :interested_by_given)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<div class="container">
  <div class="row">
		<div class="col-md-2 col-md-offset-2">
			<h3 class="text-center", style="background-color: #EEEEEE;">マイページ</h3>
		</div>
	</div>

	<div class="row">
		</br>
		<h4 class="col-md-2">自分のプロフィール</h4>
		<span><%#=link_to "編集する", edit_customers_path, class: "btn btn-info" %></span>
		<span><%#=link_to "パスワードを変更する", new_customer_password_path, class: "btn btn-info" %></span>
	</div>


<div>
	<% unless user_signed_in? && current_user.id == user.id %>
    		<div id="follow_form">
        		<% if current_user.following?(user) %>
            		<%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }, local: true) do |f| %>
                	<%= f.submit "フォローする", class: "btn" %>
            		<% end %>
        		<% else %>
            		<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
                	<div><%= hidden_field_tag :followed_id, user.id %></div>
                	<%= f.submit "あなたが既にフォローをしている人です", class: "btn btn-primary" %>
            		<% end %>
        		<% end %>
    		</div>
    		<% else %>
    		<% end %>
</div>

<div>
		<%= link_to "フォロー数", following_user_path(user) %>
		<%= user.following.count %>
</div>

<div>
	<%= link_to "フォロワー数", followers_user_path(user) %>
	<%= user.followers.count %>
</div>

	<div class="row">
		<table class="table table-hover table-bordered", border="5">





	<thead>
		<tr>
			<th width = 200px, height = 50px,>顔写真</th>
			<th width = 50px, height = 50px>氏名</th>
			<th style="width: 200px", style="height: 50px">カナ</th>
			<th style="width: 200px", style="height: 50px">職業</th>
			<th style="width: 200px", style="height: 50px">目標年収</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %></td>
			<td width = 50px, height = 50px><%= user.name %></td>
			<td><%= user.kana_name %></td>
			<td><%= user.occupation %></td>
			<td><%= user.target_income %></td>
		</tr>
	</tbody>

		<thead>
		<tr>
			<th colspan="5", style="width: 200px">自己紹介</th>
		</tr>
	</thead>

		<tbody>
		<tr>
			<td colspan="5", style="width: 200px", class="user-edit"><%= user.introduction %></td>
		</tr>
	</tbody>

			<thead>
		<tr>
			<th colspan="5", style="width: 200px">何のためにこのアプリを使っているか、どんな人を求めているか</th>
		</tr>
	</thead>

		<tbody>
		<tr>
			<td colspan="5", style="width: 200px"><%= user.for_what_application %></td>
		</tr>
	</tbody>

			<thead>
		<tr>
			<th colspan="5", style="width: 200px">私の人生の歩み</th>
		</tr>
	</thead>

		<tbody>
		<tr>
			<td colspan="5", style="width: 200px"><%= user.how_did_life %></td>
		</tr>
	</tbody>

	<thead>
		<tr>
			<th width = 200px, height = 50px>メッセージで返事を返す基準</th>
			<th width = 200px, height = 50px>時間の投資をしたい相手</th>
			<th style="width: 200px", style="height: 50px">望む労働時間</th>
			<th style="width: 200px", style="height: 50px">仕事上で人材教育、投資について考えていること</th>
			<th style="width: 200px", style="height: 50px">自分が提供できるもの（仕事において）</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td><%= user.message_level %></td>
			<td><%= user.ignore_character %></td>
			<td><%= user.want_job_time %></td>
			<td><%= user.think_job_relationship %></td>
			<td><%= user.can_offer_job %></td>
		</tr>
	</tbody>

	<thead>
		<tr>
			<th colspan="5", style="width: 200px">仕事上で人材教育、投資について考えていること</th>
		</tr>
	</thead>

		<tbody>
		<tr>
			<td colspan="5", style="width: 200px"><%= user.think_job_relationship %></td>
		</tr>
	</tbody>


	<thead>
		<tr>
			<th width = 200px, height = 50px>私が学びたいこと</th>
			<th width = 200px, height = 50px>仕事以外で興味があること、好きなこと</th>
			<th style="width: 200px", style="height: 50px">a間</th>
			<th style="width: 200px", style="height: 50px">恋愛に関して望んでいるもの</th>
			<th style="width: 200px", style="height: 50px">私が望んでいるもの</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td><%= user.what_want_learn %></td>
			<td><%= user.like_other_job %></td>
			<td><%= user.think_job_relationship %></td>
			<td><%= user.what_desire_love %></td>
			<td><%= user.what_require %></td>
		</tr>
	</tbody>



		<thead>
		<tr>
			<th colspan="5", style="width: 200px">自分の基となる経験値と、経験値から生まれた考え方</th>
		</tr>
	</thead>

		<tbody>
		<tr>
			<td colspan="5", style="width: 200px"><%= user.basic_experience %></td>
		</tr>
	</tbody>

	<thead>
		<tr>
			<th colspan="5", style="width: 200px">過去の失敗</th>
		</tr>
	</thead>

		<tbody>
		<tr>
			<td colspan="5", style="width: 200px"><%= user.past_failures %></td>
		</tr>
	</tbody>



	<thead>
		<tr>
			<th width = 200px, height = 50px>性格、好きな人のタイプ</th>
			<th width = 200px, height = 50px>自分が提供できるもの（仕事以外のことで）</th>
			<th style="width: 200px", style="height: 50px">心を動かされるきっかけに共通していること</th>
			<th style="width: 200px", style="height: 50px">coming soon</th>
			<th style="width: 200px", style="height: 50px">coming soon</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td><%= user.my_personality %></td>
			<td><%= user.can_offer_personality %></td>
			<td><%= user.interested_by_given %></td>
			<td></td>
			<td></td>
		</tr>
	</tbody>





		</table>
	</div>

</div>

app/views/users/quit.html.erb
<div class="container">
  <div class="row">
    </br>
    <h4 class="text-center font-weight-bolder">本当に退会しますか？</h4>
    <h4 class="text-center">退会すると、会員登録情報や</h4>
    <h4 class="text-center">これまでの購入履歴が閲覧できなくなります。</h4>
    <h4 class="text-center">退会する場合は、「退会する」をクリックしてください。</h4>
    </br>
  </div>
  <div class="row text-center">
    <span class="col-md-2">
      <%= link_to "退会しない（トップ画面に戻る）", root_path, class: "btn btn-info" %>
    </span>
    <span class="col-md-2">
      <%= link_to "退会する", out_users_path, method: :patch, class: "btn btn-danger" %>
    </span>
  </div>
</div>

app/views/users/show.html.erb
<div class="background-show" height="1500px" width="1500px">

	<div class="container">
	  <div class="row">
				<h3 class="text-center center-th">ユーザーページ</h3>
				 <% if flash[:notice] %>
				<div class="flash">
				<%= flash[:notice] %>
				</div>
				<% end %>
		</div>

		<div class="row">

			<div class="col-lg-2 in-lineblock text-center">
			  <div>
	    		<%= link_to "フォロー一覧", following_user_path(@user), class: "btn btn-primary" %>
	    		<%= @user.following.count %>
	      </div>
	    </div>

			<div class="col-lg-2 in-lineblock text-center">
	      <div>
	      	<%= link_to "フォロワー一覧", followers_user_path(@user), class: "btn btn-primary" %>
	      	<%= @user.followers.count %>
	      </div>
	    </div>

			<div class="col-lg-2 in-lineblock text-center">
			  <%= link_to "つぶやく", new_soliloquy_path, class: "btn btn-primary" %>
			</div>

			<div class="col-lg-2 in-lineblock text-center">
        <% if @user.id == current_user.id %>

        <% else %>
          <% if @is_room == true %>
            <%= link_to "DM画面へ", room_path(@room_id), user_id: @user.id, class: "btn btn-primary" %>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, :value=> @user.id %>
              <% end %>
              <%= f.submit "DMを始める", class: "btn btn btn-primary" %>
            <% end %>
          <% end %>
        <% end %>
	    </div>

			<div class="col-lg-2 in-lineblock text-center">
	      <%= link_to "会員情報編集画面へ", edit_user_path(@user), class: "btn btn-primary" %>
			</div>

			<div class="col-lg-2 in-lineblock text-center">
				<% unless user_signed_in? && current_user.id == @user.id %>
	    		<div id="follow_form">
	        	<% if current_user.following?(@user) %>
	           	<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete }, local: true) do |f| %>
	            	<%= f.submit "フォロー中！", class: "btn" %>
	          	<% end %>
	        	<% else %>
	            <%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
	            	<div><%= hidden_field_tag :followed_id, @user.id %></div>
	            	<%= f.submit "フォローする", class: "btn btn-info" %>
	            	<% end %>
	        	<% end %>
	    		</div>
	    	<% else %>
	    	<% end %>
			</div>
		</div>
	<br>

		<div class="row">

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">顔写真</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= attachment_image_tag @user, :profile_image, :fill, 300, 300, fallback: "no_image.jpg", size: '300x300' %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">氏名</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.name %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">カナ</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.kana_name %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">自己紹介</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.introduction %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">アプリの利用目的、どんな人を求めているか</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.for_what_application %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">メッセージで返事を返す基準</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.message_level %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">時間を投資をしたい相手の特徴</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.ignore_character %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">現在の職業</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.occupation %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">働くことに関して考えていること</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.think_to_job %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">望む労働時間</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.want_job_time %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">仕事上で人材教育、投資について考えていること</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.think_job_relationship %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">自分が提供できるもの（仕事において）</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.can_offer_job %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">目標年収</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.target_income %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">学びたいこと</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.what_want_learn %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">仕事以外に好きなもの</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.like_other_job %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">恋愛に関して望んでいるもの</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.what_desire_love %></td>
				</tbody>
			</table>


			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">私の人生の歩み</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.how_did_life %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">過去の失敗</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.past_failures %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">自分の基となる経験値と、経験値から生まれた考え方</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.basic_experience %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">望んだ生き方、求めているもの</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.what_require %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">性格、好きな人のタイプ</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.my_personality %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">自分が提供できるもの（仕事に関係しないことで）</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.can_offer_personality %></td>
				</tbody>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">求めている人間関係と精神状態の関係</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.request_relationship_spirit  %></td>
				</tbody>
			</table>


			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">心を動かされること</th>
				  </tr>
				</thead>
				<tbody>
				  <td class="text-center", style="width: 3000px"><%= @user.interested_by_given %></td>
				</tbody>
			</table>

		</div>

	</div>


	<%= render "soliloquies/index", soliloquies: @soliloquies %>


</div>

app/views/users/show_follow.html.erb
<div class="background-show" height="1500px" width="1500px">
  <div class="row">
      <section class="text-center">
          <%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: "100×100") %>
          <h2><%= @user.name %></h2>
      </section>
      <section class="">
        <% if @users.any? %>
            <table class="text-center table center-index">
              <thead>
                <tr>
                  <th class="text-center">顔写真</th>
                  <th class="text-center">名前</th>
                  <th class="text-center">フォロー数</th>
                  <th class="text-center">フォワー数</th>
                </tr>
              </thead>
              <% @users.each do |user| %>
                <tbody>
                  <tr>
                    <td width="120">
                      <%= link_to user_path(user) do %>
                        <%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: "100x100") %>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to user_path(user) do %>
                        <%= user.name %>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to following_user_path(user) do %>
                        <%= user.following.count %>人
                      <% end %>
                    </td>
                    <td>
                      <%= link_to following_user_path(user) do %>
                        <%= user.followers.count %>人
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              <% end %>
            </table>
        <% end %>
      </section>
        <%= will_paginate %>
  </div>
</div>