config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root "soliloquies#top"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      patch :out
    end

    member do
      get :following, :followers
      get :quit
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :messages, :only => [:create]

  resources :rooms, :only => [:create, :show, :index]

  resources :relationships, only: [:create, :destroy]

  resources :soliloquies do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get "about" => "soliloquies#about"

  get "first" => "users#first"
end

app/models/soliloquy.rb
class Soliloquy < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { in: 2..30 }
  validates :object, presence: true, length: { in: 2..1000 }
  validates :what_do, presence: true, length: { in: 2..1000 }
  validates :how_feel, presence: true, length: { in: 2..1000 }
  validates :must_and_can, presence: true, length: { in: 2..1000 }
  validates :did_action, presence: true, length: { in: 2..1000 }
  validates :purpose_soliloquy, presence: true, length: { in: 2..1000 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/soliloquies_controller.rb
class SoliloquiesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :show]

  def top
  end

  def about
  end

  def index
    @users = User.all
    @soliloquies = Soliloquy.all
    @post_comment = PostComment.new
  end

  def new
    @soliloquy = Soliloquy.new
  end

  def create
    @soliloquy = Soliloquy.new(soliloquy_params)
    @soliloquy.score = Language.get_data(soliloquy_params[:object])
    @soliloquy.title_score = Language.get_data(soliloquy_params[:title])
    @soliloquy.what_do_score = Language.get_data(soliloquy_params[:what_do])
    @soliloquy.how_feel_score = Language.get_data(soliloquy_params[:how_feel])
    @soliloquy.must_and_can_score = Language.get_data(soliloquy_params[:must_and_can])
    @soliloquy.did_action_score = Language.get_data(soliloquy_params[:did_action])
    @soliloquy.porpose_soliloquy_score = Language.get_data(soliloquy_params[:purpose_soliloquy])

    @soliloquy.user_id = current_user.id
    if @soliloquy.save
      redirect_to soliloquy_path(@soliloquy)
    else
      render :new
    end
  end

  def destroy
    @soliloquy = Soliloquy.find(params[:id])
    @soliloquy.user_id = current_user.id
    @soliloquy.destroy
    redirect_to soliloquies_path
  end

  def show
    @soliloquy = Soliloquy.find(params[:id])
    if @soliloquy.user.is_deleted == "Invaild"
      flash[:notice] = "退会したユーザーの投稿です"
      redirect_to soliloquies_path
    end
    @post_comment = PostComment.new
  end

  private

  def soliloquy_params
    params.require(:soliloquy).permit(:title, :object, :what_do, :how_feel,
                                      :must_and_can, :did_action, :purpose_soliloquy)
  end
end

app/helpers/soliloquies_helper.rb
module SoliloquiesHelper
end

app/views/soliloquies/_index.html.erb
<div class="solindex-background">
    <table class="text-center table">
      <thead>
        <tr>
          <th class="text-center">投稿者写真</th>
          <th class="text-center">つぶやきタイトル</th>
          <th class="text-center">稼働中/退会済み</th>
          <th class="text-center">つぶやき詳細へ</th>
          <th class="text-center">何を思ったか</th>
          <th class="text-center">ユーザー名</th>
        </tr>
      </thead>


        <% soliloquies.each do |soliloquy| %>
          <% if soliloquy.user.is_deleted == "Invaild" %>
          <% else %>
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(soliloquy.user) do %>
                  <%= attachment_image_tag soliloquy.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: "100x100" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to soliloquy_path(soliloquy) do %>
                  <%= soliloquy.title %></td>
                  <% end %>
                </td>
                <td>
                  <% if soliloquy.user.is_deleted == "Availble" %>
                  <%= "稼働中" %>
                  <% else %>
                  <%= "退会済み" %>
                  <% end %>
                </td>
                <td class="btn btn-default"><%= link_to "詳細", soliloquy_path(soliloquy) %></td>
                <td><%= soliloquy.how_feel %></td>
                <td><%= soliloquy.user.name %></td>
              </tr>
          <% end %>
        <% end %>
  　</table>
</div>

app/views/soliloquies/about.html.erb
<div class="about">
  <h1>-about-</h1>

  <h2>このウェブサービスは次のような人のためにあります</h2>
  <h3>目的1 自分が求めている人間関係作りが成功しやすくしたい</h3>
  <h3>目的2 難しいことも伝えあえるような人間関係を作りたい</h3>
  <h3>目的3 人間関係を作るための相手の情報を正確に取得したい</h3>

<br>

  <p>自分が望んでいる人間関係を構築することってなかなか難しいことではありませんか？</p>
  <p>いろんな現象が混じりあった出来事を正確に簡単に伝えられなくてもどかしくないですか？</p>
  <p>信用することって難しいですよね？</p>


<br>
  <h2>そんなあなたの問題を全て解決します</h2>
  <div>

  </div>
</div>

app/views/soliloquies/index.html.erb
<%= render "soliloquies/index", soliloquies: @soliloquies, user: @user %>

app/views/soliloquies/new.html.erb
<div class="container solshow-background">
  <div class="row">
    <div style="">
      <h4 class="text-center">あなたの思いを正確につぶやこう</h4>
    </div>
  </div>
	<br>
	<br>

	<div class="row">

			<div class="">
        <%= form_with model: @soliloquy, url: soliloquies_path, local: true do |f| %>
					<%= render 'layouts/errors', resource: @soliloquy %>
		        <% if flash[:notice] %>
							<div class="flash">
								<%= flash[:notice] %>
							</div>
						<% end %>
<br>


        <br>
					<table class="table">

						<thead>
							<tr>
								<th class="text-center center-th" ,width = 200px, height = 50px>つぶやきタイトル</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.text_field :title, autocomplete: "title", :size=>"50", class:"center" %></td>
							</tr>
						</tbody>

						<thead>
							<tr>
								<th class="text-center center-th" , width = 200px, height = 50px>何に対し(どのような現象に)</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.text_area :object, autofocus: true, autocomplete: "object", :size=>"150", class:"center", :style=>"height: 100px" %></td>
							</tr>
						</tbody>

						<thead>
							<tr>
								<th class="text-center center-th" , width = 200px, height = 50px>何をして（どんな立場か、どんなタイミングで見たか）</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.text_area :what_do, autofocus: true, autocomplete: "what_do", :size=>"150", class:"center", :style=>"height: 100px" %></td>
							</tr>
						</tbody>

						<thead>
							<tr>
								<th class="text-center center-th" , width = 200px, height = 50px>何を思ったか</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.text_area :how_feel, autofocus: true, autocomplete: "how_feel", :size=>"150", class:"center", :style=>"height: 100px" %></td>
							</tr>
						</tbody>

						<thead>
							<tr>
								<th class="text-center center-th" , width = 200px, height = 50px>自分は何をしなければいけないのか？また似た分野では何ができているか？</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.text_area :must_and_can, autofocus: true, autocomplete: "must_do", :size=>"150", class:"center", :style=>"height: 100px" %></td>
							</tr>
						</tbody>

						<thead>
							<tr>
								<th class="text-center center-th" , width = 200px, height = 50px>自分ができることに対し何を今までしてきたか</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.text_area :did_action, autofocus: true, autocomplete: "did_action", :size=>"150", class:"center", :style=>"height: 100px" %></td>
							</tr>
						</tbody>

						<thead>
							<tr>
								<th class="text-center center-th" , width = 200px, height = 50px>このつぶやきは何が目的か</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.text_area :purpose_soliloquy, autofocus: true, autocomplete: "purpose_soliloquy", :size=>"150", class:"center", :style=>"height: 100px" %></td>
							</tr>
						</tbody>

						<thead>
							<tr>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center center-th"><%= f.submit "つぶやく", class:"btn btn-success sign_up" %></td>
							</tr>
						</tbody>

					</table>
      </div>
    </div>
  			<% end %>

</div>

app/views/soliloquies/show.html.erb
<div class="container">

	<div class="row">
		<h2 class="text-center tubuyaki-title">つぶやき詳細</h2>
	</div>

<br>

		<div class="row text-center tubuyaki-title">
			<div class="col-lg-6">
				<%= link_to "投稿ユーザーのページへ", user_path(@soliloquy.user_id) , class: "btn btn-primary" %>
			</div>
			<div class="col-lg-6">
				<%= link_to "このつぶやきを削除する", soliloquy_path(@soliloquy), method: :delete, class: "btn btn-danger" %>
			</div>
		</div>


		<br>

  <div class="row">
			<div class="solshow-background">

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">タイトル</th>
				  </tr>
				</thead>
				<tbody>
					<tr><td class="text-center", style="width: 3000px"><%= @soliloquy.title %></td></tr>
				</tbody>
					<tr><td class="text-center sentiment-score">タイトルの感情分析スコア[<%= @soliloquy.title_score %>]</td></tr>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">何に対して</th>
				  </tr>
				</thead>
				<tbody>
					<tr><td class="text-center", style="width: 3000px"><%= @soliloquy.object %></td></tr>
				</tbody>
					<tr><td class="text-center sentiment-score">何に対しての感情分析スコア[<%= @soliloquy.score %>]</td></tr>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">何をして（何を見て）</th>
				  </tr>
				</thead>
				<tbody>
					<tr><td class="text-center", style="width: 3000px"><%= @soliloquy.what_do %></td></tr>
				</tbody>
					<tr><td class="text-center sentiment-score">何をしての感情分析スコア[<%= @soliloquy.what_do_score %>]</td></tr>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">どう感じたか</th>
				  </tr>
				</thead>
				<tbody>
					<tr><td class="text-center", style="width: 3000px"><%= @soliloquy.how_feel %></td></tr>
				</tbody>
				<tr><td class="text-center sentiment-score">本文の感情分析スコア[<%= @soliloquy.how_feel_score %>]</td></tr>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">自分はそれに対し何をしなければいけないのか？また似た分野では何ができているか？</th>
				  </tr>
				</thead>
				<tbody>
					<tr><td class="text-center", style="width: 3000px"><%= @soliloquy.must_and_can %></td></tr>
				</tbody>
					<tr><td class="text-center sentiment-score">何をしなければいけない感情分析スコア[<%= @soliloquy.must_and_can_score %>]</td></tr>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">自分ができることに対して何を今までしてきたか</th>
				  </tr>
				</thead>
				<tbody>
					<tr><td class="text-center", style="width: 3000px"><%= @soliloquy.did_action %></td></tr>
				</tbody>
				<tr><td class="text-center sentiment-score">自分ができることの感情分析スコア[<%= @soliloquy.did_action_score %>]</td></tr>
			</table>

			<table class="table table-hover table-striped w-100">
				<thead>
				  <tr>
				    <th class="text-center center-th", style="width: 3000px">このつぶやきは何が目的か</th>
				  </tr>
				</thead>
				<tbody>
					<tr><td class="text-center", style="width: 3000px"><%= @soliloquy.purpose_soliloquy %></td></tr>
				</tbody>
				<tr><td class="text-center sentiment-score">つぶやきの目的感情分析スコア[<%= @soliloquy.porpose_soliloquy_score %>]</td></tr>
			</table>

					<tr>
						<td>
							<div id="favorites_buttons_<%= @soliloquy.id %>">
							<%= render "favorites/favorite", soliloquy: @soliloquy %>
							</div>
						</td>
					</tr>

					<tr>
						<td>
							<!--<div id="post_comment_<%#= @post_comment.id %>">-->
								<%#= render "post_comments/post_comment", soliloquy: @soliloquy, post_comment: @post_comment %>
								<div>


								<%= form_with(model: @post_comment, url: soliloquy_post_comments_path(@soliloquy), remote: true) do |f| %>


								  	<div class="row">
								    	<div class="col-sm-12">
								      		<%= f.text_area :comment, rows:'2', class: "form-control comment-create", placeholder: "コメントをここに" %>
								    	</div>
								  	</div>
								  	<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
								  <% end %>




								<%= render partial: 'post_comments/post_comment', locals: { soliloquy: @soliloquy, post_comment: @post_comment} %>

							</div>
						</td>
					</tr>

			</div>

			<br>
			<br>
			<br>
			<br>


	</div>
</div>

app/views/soliloquies/top.html.erb
<h1 align="center", class="top4">我々が心の底から望む人間関係を探しに行こう</h1>

<div class="top-background" height="1500px" width="1500px">

  <div>
    <h1 align="center", class="top2">friend partner</h1>
  </div>

  <div class="top-container">
    <div align="center", class="top5">

        <li><%= link_to "新規登録", new_user_registration_path, class:"btn btn-success center" %></li>
        <li><%= link_to "ログイン", new_user_session_path, class:"btn btn-info center" %></li>
        <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:"btn btn-warning center" %></li>

    </div>

    <div class="top3">
      <h1 align="center">True deep humanity</h1>
      <br>
      <h1 align="center">And</h1>
      <br>
      <h1 align="center">Real friend</h1>
    </div>
  </div>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
</div>