config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root "soliloquies#top"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      patch :out
    end

    member do
      get :following, :followers
      get :quit
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :messages, :only => [:create]

  resources :rooms, :only => [:create, :show, :index]

  resources :relationships, only: [:create, :destroy]

  resources :soliloquies do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get "about" => "soliloquies#about"

  get "first" => "users#first"
end

app/views/layouts/_errors.html.erb
<div class="error">
  <% if resource.errors.any? %>
    <div id="error_explanation", class="alert alert-danger">
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>friend-partner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script src="https://kit.fontawesome.com/fde22234ab.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
    <body class="body">
      <header class="navbar navbar-inverse">
        <div class="container">
          <nav class='nav navbar-nav navbar-left'>

          <%= link_to root_path do %>
            <span><%= image_tag "friend-logo6.png", :size => "200x70" %></span>
          <% end %>

          </nav>
            <nav>
              <ul class="nav navbar-nav navbar-right" style="margin-top: 20px;">

                <% if user_signed_in? %>
                  <li>
                    <h4 style="color: white; margin-top: 15px;"><%= current_user.name %>さんでログイン中です</h4>
                  </li>
                  <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                  <li><%= link_to "会員一覧", users_path %></li>
                  <li><%= link_to "みんなのつぶやき", soliloquies_path %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "about", about_path %></li>
                  <li><%= link_to "新規登録", new_user_registration_path %></li>
                  <li><%= link_to "ログイン", new_user_session_path %></li>
                  <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></li>
                <% end %>
              </ul>
            </nav>
        </div>
  </header>
  <div class="body">
    <%= yield %>
  </div>
  <footer class="navbar navbar-inverse" style= "margin-bottom: 0;">
    <h3 align = "right">friend partner for portfolio...</h3>
  </footer>
  </body>

</html>